### ISSUE TITLE
[Bug] Guild Pack Discord Invite Link Invalid in README

### ISSUE THREAD

**Issue by aphix** [Dimencia/LuteBot3#2]
Discord link to [Guild Library](https://github.com/Dimencia/LuteBot3/blob/master/README.md#L33) does not appear to work.

Repo is broken.

=P

Any chance that pack still exists, as it seems important to run (based on prior instructions in the README)?

Side note: Just scanned through a chunk of your changes from v2 and it looks solid, very cool. Awesome work.

**Comment by Dimencia** [comment]
Guild pack is no longer available or necessary.  Didn't see this for a while, sorry.  A REST API search of our entire guild library is available instead
