### ISSUE TITLE
Nothing Happens When LuteBot.exe is launched

### ISSUE THREAD

**Issue by baloof1621** [Dimencia/LuteBot3#6]
Just downloaded LuteBot and i extracted to a folder on my desktop. Went into properties and made sure Windows defender wouldnt block it, then attempted running as admin. Each time I tried to run LuteBot nothing would happen, except "Windows Problem Reporting" would pop up in task manager, and an empty Config folder would be created in the LuteBot folder. I have tried restarting and redownloading to no avail.

**Comment by Dimencia** [comment]
This should be fixed, I accidentally uploaded a broken 3.0.9 and have updated the release (recently).  Re-download and let me know if you still have this problem

**Comment by baloof1621** [comment]
works! Thank you.
