### ISSUE TITLE
"Sporadic" playing

### ISSUE THREAD

**Issue by Shaggy-Iguana** [Dimencia/LuteBot3#7]
I love lutebot 3.0, but every time I use it, after a few minutes it will break down. When I start a song, lutebot will only play sporadically - 2 seconds or so of music every 1-2 seconds, skipping over parts of the song. This is (usually) fixed - for some reason - when I exit out, right click the run file and hit 'troubleshoot compatibilty' and reopen lutebot. And as a side note - if I try to refresh the song, enter a new midi file or change keybinds during the times when its broken, it sends back an error, saying the path to the Profiles folder was blocked. 

I don't know if this is something that _I'm_ doing wrong, as I'm new to this, or if its the programs issue. Let me know if this is something you've encountered before, or if its something you've seen happen to people who didn't set it up correctly, or whatever. If you need screenshots or recordings of the problem, I can provide them.

Thank you!

**Comment by Dimencia** [comment]
Usually if there are problems accessing files it'll just crash, so this is a bit weird.

Running as administrator may work

But also make sure the folder and executable are not in a protected folder, like Program Files.  Documents, Downloads, etc are all fine.  

Antivirus might be scanning the files constantly and having problems?  Or your HD may be full.  No idea, really
