### ISSUE TITLE
Lutebot not launching

### ISSUE THREAD

**Issue by arnie2** [Dimencia/LuteBot3#8]
Hello, I downloaded the latest version this weekend, and it was working fine until I noticed it was no longer open. I thought I had accidentally closed it, but when I try and launch it again it will not launch. I don't see anything open related to it in Task Manager either. Any advice on how to fix this? Thanks

**Comment by Dimencia** [comment]
Make sure to delete all old files or extract to a new folder and redownload the latest version if you haven't, it has been updated regularly.  Running as admin is necessary if you run the file from somewhere other than your documents/downloads/personal folders.  And if all else fails, contact me on the Bard's Guild Discord (listed in the project readme)
